# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54efe8b9039c7237883019c17b49ca8d486c4dac1c6a94a5012c99dc4562c45608730c8126809ac019886a429f88bc950ceae254cbc8c802052e5f4ae1ce9db7

test:
  secret_key_base: 5eb927384a8e7e282b24e0c437b57ad0a150baee28b838113a35ad6e0da9627be5591efc9be9c7ee452c8a7657ae361210f44902257ff06745d44b48fdcc70ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
